name: julian Echeverry Portfolio
favicon: null
layout_spectrum: 0.32032986963167787
typography_spectrum: 0.7432623710483313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9868632000871003
  lightness: 0.3296261024661362
  saturation: 0.3266245878767222
  rhythmicContrast: 0.9479544647037983
purpose: []
